#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# cntkrun <CNTK config file name> <additional CNTK args>
DeleteModelsAfterTest=0
cntkrun cntk.cntk 'forceDeterministicAlgorithms=true makeMode=false' || exit $?
