#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -ex

if [[ -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
    if [ "$OS" == "Windows_NT" ]; then
       CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY="$(cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY)"
    fi
    ConfigDir="$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Config/Internal"
    [[ -d "$ConfigDir" ]]
else
    echo Config not available.
    exit 0
fi

cntkrun cntk.cntk 'forceDeterministicAlgorithms=true makeMode=true'
